SportStore/Models/Cart.cs
namespace SportStore.Models
{
    public class Cart //корзина
    {
        public List<CartLine> Lines { get; set; } = new List<CartLine>();

        public void AddItem(Product product, int quantity) // добавление в корзину
        {
            CartLine line = Lines.Where(p => p.Product.ProductID == product.ProductID)
                .FirstOrDefault();
            if(line==null)
            {
                Lines.Add(new CartLine()
                {
                    Product = product,
                    Quantity = quantity
                });
            }
            else
            {
                line.Quantity += quantity;
            }
        }

        public void RemoveLine(Product product) // удаление элемента из корзины
        {
            Lines.RemoveAll(l => l.Product.ProductID == product.ProductID);
        }

        public decimal ComputeTotalValue() //расчёт общей стоимости покупки
        {
            return Lines.Sum(e => e.Product.Price * e.Quantity);
        }

        public void Clear() // очистка корзины
        {
            Lines.Clear();
        }
    }

    //определяет выбранный товар
    public class CartLine
    {
        public int CartLineId { get; set; }

        public Product Product { get; set; }

        public int Quantity { get; set; }
    }
}

SportStore/Models/EFStoreRepository.cs
namespace SportStore.Models
{
    // Репозиторий для работы с базой данных с использованием Entity Framework
    public class EFStoreRepository : IStoreRepositiry
    {
        // Контекст базы данных
        private StoreDbContext context;

        // Конструктор для внедрения зависимости контекста базы данных
        public EFStoreRepository(StoreDbContext ctx)
        {
            context = ctx;
        }

        // Свойство, предоставляющее доступ к коллекции продуктов
        public IQueryable<Product> Products => context.Products;
    }
}

SportStore/Models/IStoreRepositiry.cs
namespace SportStore.Models
{
    public interface IStoreRepositiry
    {
        IQueryable<Product>Products { get; }
    }
}

SportStore/Models/Product.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace SportStore.Models
{
    // Модель продукта
    public class Product
    {
        // Идентификатор продукта
        public long ProductID { get; set; }

        // Название продукта
        public string Name { get; set; }

        // Описание продукта
        public string Description { get; set; }

        // Цена продукта
        [Column(TypeName = "decimal(8,2)")]
        public decimal Price { get; set; }

        // Категория продукта
        public string Category { get; set; }
    }
}

SportStore/Models/SeedData.cs
using Microsoft.EntityFrameworkCore;

namespace SportStore.Models
{
    // Класс для заполнения базы данных начальными данными
    public class SeedData
    {
        // Метод для обеспечения наличия начальных данных
        public static void EnsurePopulated(IApplicationBuilder app)
        {
            // Получаем контекст базы данных из сервисов приложения
            StoreDbContext context = app.ApplicationServices.CreateScope()
                .ServiceProvider.GetRequiredService<StoreDbContext>();

            // Применяем все ожидающие миграции, если они есть
            if (context.Database.GetPendingMigrations().Any())
            {
                context.Database.Migrate();
            }

            // Если в базе данных нет продуктов, добавляем начальные данные
            if (!context.Products.Any())
            {
                context.Products.AddRange(
                    new Product
                    {
                        Name = "Каяк",
                        Description = "Лодка для одного человека",
                        Category = "Водный спорт",
                        Price = 275
                    },
                    new Product
                    {
                        Name = "Спортивный рюкзак",
                        Description = "Рюкзак для спортинвентаря",
                        Category = "Рюкзаки и сумки",
                        Price = 20
                    },
                    new Product
                    {
                        Name = "Футбольный мяч",
                        Description = "Установленный FIFA размер и вес",
                        Category = "Футбол",
                        Price = 15
                    },
                    new Product
                    {
                        Name = "Куртка зимняя Puma",
                        Description = "Зимняя одежда",
                        Category = "Верхняя одежда",
                        Price = 35
                    },
                    new Product
                    {
                        Name = "Волейбольный мяч",
                        Description = "Стандарт",
                        Category = "Волейбол",
                        Price = 11
                    }
                );
                // Сохраняем изменения в базе данных
                context.SaveChanges();
            }
        }
    }
}

SportStore/Models/StoreDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace SportStore.Models
{
    // Контекст базы данных для взаимодействия с базой данных
    public class StoreDbContext : DbContext
    {
        // Конструктор контекста базы данных, принимающий опции контекста
        public StoreDbContext(DbContextOptions<StoreDbContext> options) : base(options)
        {
        }

        // Набор сущностей продуктов в базе данных
        public DbSet<Product> Products { get; set; }
    }
}

SportStore/Models/ViewModels/PaginInfo.cs
namespace SportStore.Models.ViewModels
{
    public class PaginInfo
    {
        public int TotalItems { get; set; }

        public int ItemsPerPage { get; set; }

        public int CurrentPage { get; set; }

        public int TotalPage()
        {
            return (int) Math.Ceiling((decimal) TotalItems / ItemsPerPage);
        }
    }
}

SportStore/Models/ViewModels/ProductsListViewModel.cs
namespace SportStore.Models.ViewModels
{
    public class ProductsListViewModel
    {
        public IEnumerable<Product> Products { get; set;}

        public PaginInfo PaginInfo { get; set;}

        public string CurrentCategory { get; set; }
    }
}

SportStore/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportStore.Models;

namespace SportStore.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IStoreRepositiry repositiry;

        public NavigationMenuViewComponent (IStoreRepositiry repositiry)
        {
            this.repositiry = repositiry;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(repositiry.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x));
        }
    }
}

SportStore/Pages/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SportStore.Infrastructure;
using SportStore.Models;

namespace SportStore.Pages
{
    public class CartModel : PageModel
    {
        private IStoreRepositiry repositiry;

        public CartModel (IStoreRepositiry repositiry)
        {
            this.repositiry = repositiry;
        }

        public Cart Cart { get; set; }

        public string ReturnUrl { get; set; }

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
            Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
        }

        public IActionResult OnPost(long productId, string returnUrl)
        {
            Product product = repositiry.Products
                .FirstOrDefault(p => p.ProductID == productId);
            Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
            Cart.AddItem(product, 1);
            HttpContext.Session.SetJson("cart", Cart);
            return RedirectToPage(new { returnUrl = returnUrl });
        }
    }
}

SportStore/Pages/Cart.cshtml
@page
@model CartModel

<h2>Ваше корзина</h2>
<table class="table table-bordered table-striped">
<thead>
    <tr>
        <th>Количество</th>
         <th>Продукт</th>
          <th class="text-right">Цена за ед.</th>
           <th class="text-right">Итого</th>
    </tr>
</thead>
<tbody>
    @foreach(var line in Model.Cart.Lines)
        {
            <tr>
                <td class="text-center">@line.Quantity</td>
                 <td class="text-left">@line.Product.Name</td>
                  <td class="text-right">@line.Product.Price.ToString("c")</td>
                   <td class="text-right">
                       @((line.Quantity*line.Product.Price).ToString())
                   </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Итого:</td>
            <td class="text-right">@Model.Cart.ComputeTotalValue().ToString("c")</td>
        </tr>
    </tfoot>
</table>
<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Продолжить покупки</a>
</div>

SportStore/Pages/_CartLayout.cshtml
<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>

<body>

    <div class="bg-dark textbg-white p-2">
        <span class="navbar-brand ml-2"> SPORTS STORE </span>
    </div>

    <div class="m-1 p-1">
        @RenderBody()
    </div>

</body>

</html>

SportStore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h4> Welcome to SportStore </h4>

@model ProductsListViewModel

    @foreach (var p in Model.Products)
    {
        <partial name="ProductSummary" model="p" />
    }

<div page-model="@Model.PaginInfo" page-action="Index"
page-classes-enabled="true"
page-class="btn" page-class-normal="btn-outline-dark"
page-class-selected="btn-primary" class="btn-group pull-right m-1"
page-url-category="@Model.CurrentCategory" class="btn-group pull-right m-1">
</div>

SportStore/Views/Shared/Components/NavigationMenu/Default.cshtml
@model IEnumerable<string>
<div class="d-grid gap-2">
    <a class="btn btn-block btn-outline-secondary" asp-action="Index"
    asp-controller="Home" asp-route-category="">
    Все товары
    </a>
</div>

@foreach (string category in Model)
{
    <div class="d-grid gap-2">
        <a class="btn 
        @(category==ViewBag.SelectedCategory ? "btn-primary" : "btn-outline-primary")
        asp-action="Index"
        asp-controller="Home" asp-route-category="@category"
        asp-route-productPage="1">
        @category <br />
        </a>
    </div>
}

SportStore/Views/Shared/ProductSummary.cshtml
@namespace SportStore.Pages
@model Product
<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">

        <h4>
            @Model.Name
            <span class="badge bg-primary" style="float:right">
                <small> @Model.Price.ToString("c") </small>
            </span>
        </h4>
    </div>
    <form id="@Model.ProductID" asp-page="/Cart" method="post">
        <input type="hidden" asp-for="ProductID" />
        <input type="hidden" name="returnURL"
            value="@ViewContext.HttpContext.Request.PathAndQuery()"/>
        <span class="card-text p-1">
            @Model.Description
            <button type="submit"
                class="btn btn-success btn-sm pull-right"
                style="float:right">
                Добавить в корзину
            </button>
        </span>
    </form>
</div>

SportStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SportStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SportStore.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2"> SPORTS STORE </span>
    </div>
    <div class="row m-1 p-1">
        <div id="categories" class="col-3"> 
            <vc:navigation-menu/>
        </div>

    <div class="col-9"> 
            @RenderBody()
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SportStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>